# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notDefteri.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(738, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pln_textedit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pln_textedit.setGeometry(QtCore.QRect(0, 0, 741, 501))
        self.pln_textedit.setObjectName("pln_textedit")
        self.pushKaydetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pushKaydetBtn.setGeometry(QtCore.QRect(0, 520, 370, 28))
        self.pushKaydetBtn.setObjectName("pushKaydetBtn")
        self.pushTemizleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pushTemizleBtn.setGeometry(QtCore.QRect(370, 520, 370, 28))
        self.pushTemizleBtn.setObjectName("pushTemizleBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 738, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushKaydetBtn.setText(_translate("MainWindow", "Kaydet"))
        self.pushTemizleBtn.setText(_translate("MainWindow", "Temizle"))
