# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AfetYonetimi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Afet_Yonetimi(object):
    def setupUi(self, Afet_Yonetimi):
        Afet_Yonetimi.setObjectName("Afet_Yonetimi")
        Afet_Yonetimi.resize(400, 300)
        self.label = QtWidgets.QLabel(Afet_Yonetimi)
        self.label.setGeometry(QtCore.QRect(150, 120, 91, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Afet_Yonetimi)
        QtCore.QMetaObject.connectSlotsByName(Afet_Yonetimi)

    def retranslateUi(self, Afet_Yonetimi):
        _translate = QtCore.QCoreApplication.translate
        Afet_Yonetimi.setWindowTitle(_translate("Afet_Yonetimi", "Form"))
        self.label.setText(_translate("Afet_Yonetimi", "Afet Yönetimi"))
