# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BilgisayarliGoru.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BilgisayarliGoru(object):
    def setupUi(self, BilgisayarliGoru):
        BilgisayarliGoru.setObjectName("BilgisayarliGoru")
        BilgisayarliGoru.resize(400, 313)
        self.label = QtWidgets.QLabel(BilgisayarliGoru)
        self.label.setGeometry(QtCore.QRect(130, 100, 131, 20))
        self.label.setObjectName("label")

        self.retranslateUi(BilgisayarliGoru)
        QtCore.QMetaObject.connectSlotsByName(BilgisayarliGoru)

    def retranslateUi(self, BilgisayarliGoru):
        _translate = QtCore.QCoreApplication.translate
        BilgisayarliGoru.setWindowTitle(_translate("BilgisayarliGoru", "Form"))
        self.label.setText(_translate("BilgisayarliGoru", "Bilgisayarlı Görü"))
