# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Biyoteknoloji_Inovasyon.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BiyoteknolojiInovasyon(object):
    def setupUi(self, BiyoteknolojiInovasyon):
        BiyoteknolojiInovasyon.setObjectName("BiyoteknolojiInovasyon")
        BiyoteknolojiInovasyon.resize(400, 300)
        self.label = QtWidgets.QLabel(BiyoteknolojiInovasyon)
        self.label.setGeometry(QtCore.QRect(130, 120, 141, 16))
        self.label.setObjectName("label")

        self.retranslateUi(BiyoteknolojiInovasyon)
        QtCore.QMetaObject.connectSlotsByName(BiyoteknolojiInovasyon)

    def retranslateUi(self, BiyoteknolojiInovasyon):
        _translate = QtCore.QCoreApplication.translate
        BiyoteknolojiInovasyon.setWindowTitle(_translate("BiyoteknolojiInovasyon", "Form"))
        self.label.setText(_translate("BiyoteknolojiInovasyon", "Biyoteknoloji İnovasyon"))
