# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Iletisim.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Iletisim(object):
    def setupUi(self, Iletisim):
        Iletisim.setObjectName("Iletisim")
        Iletisim.resize(400, 300)
        self.label = QtWidgets.QLabel(Iletisim)
        self.label.setGeometry(QtCore.QRect(150, 120, 55, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Iletisim)
        QtCore.QMetaObject.connectSlotsByName(Iletisim)

    def retranslateUi(self, Iletisim):
        _translate = QtCore.QCoreApplication.translate
        Iletisim.setWindowTitle(_translate("Iletisim", "Form"))
        self.label.setText(_translate("Iletisim", "İletişim"))
