# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Instagram.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Instagram(object):
    def setupUi(self, Instagram):
        Instagram.setObjectName("Instagram")
        Instagram.resize(400, 300)
        self.label = QtWidgets.QLabel(Instagram)
        self.label.setGeometry(QtCore.QRect(150, 90, 71, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Instagram)
        QtCore.QMetaObject.connectSlotsByName(Instagram)

    def retranslateUi(self, Instagram):
        _translate = QtCore.QCoreApplication.translate
        Instagram.setWindowTitle(_translate("Instagram", "Form"))
        self.label.setText(_translate("Instagram", "İnstagram"))
