# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Linkedin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Linkedin(object):
    def setupUi(self, Linkedin):
        Linkedin.setObjectName("Linkedin")
        Linkedin.resize(400, 300)
        self.label = QtWidgets.QLabel(Linkedin)
        self.label.setGeometry(QtCore.QRect(160, 140, 71, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Linkedin)
        QtCore.QMetaObject.connectSlotsByName(Linkedin)

    def retranslateUi(self, Linkedin):
        _translate = QtCore.QCoreApplication.translate
        Linkedin.setWindowTitle(_translate("Linkedin", "Form"))
        self.label.setText(_translate("Linkedin", "Linkedin"))
