# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MedikalTeknolojiler.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Medikal(object):
    def setupUi(self, Medikal):
        Medikal.setObjectName("Medikal")
        Medikal.resize(400, 300)
        self.label = QtWidgets.QLabel(Medikal)
        self.label.setGeometry(QtCore.QRect(120, 110, 151, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Medikal)
        QtCore.QMetaObject.connectSlotsByName(Medikal)

    def retranslateUi(self, Medikal):
        _translate = QtCore.QCoreApplication.translate
        Medikal.setWindowTitle(_translate("Medikal", "Form"))
        self.label.setText(_translate("Medikal", "MEDİKAL TEKNOLOJİLER"))
