# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SaglikVeIlkYardim.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaglikVeIlkYardim(object):
    def setupUi(self, SaglikVeIlkYardim):
        SaglikVeIlkYardim.setObjectName("SaglikVeIlkYardim")
        SaglikVeIlkYardim.resize(400, 300)
        self.label = QtWidgets.QLabel(SaglikVeIlkYardim)
        self.label.setGeometry(QtCore.QRect(130, 110, 121, 16))
        self.label.setObjectName("label")

        self.retranslateUi(SaglikVeIlkYardim)
        QtCore.QMetaObject.connectSlotsByName(SaglikVeIlkYardim)

    def retranslateUi(self, SaglikVeIlkYardim):
        _translate = QtCore.QCoreApplication.translate
        SaglikVeIlkYardim.setWindowTitle(_translate("SaglikVeIlkYardim", "Form"))
        self.label.setText(_translate("SaglikVeIlkYardim", "Sağlık ve İlk Yardım"))
