# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Twitter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Twitter(object):
    def setupUi(self, Twitter):
        Twitter.setObjectName("Twitter")
        Twitter.resize(400, 300)
        self.label = QtWidgets.QLabel(Twitter)
        self.label.setGeometry(QtCore.QRect(130, 110, 61, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Twitter)
        QtCore.QMetaObject.connectSlotsByName(Twitter)

    def retranslateUi(self, Twitter):
        _translate = QtCore.QCoreApplication.translate
        Twitter.setWindowTitle(_translate("Twitter", "Form"))
        self.label.setText(_translate("Twitter", "Twitter"))
